### ISSUE TITLE
Decide on deployment / hosting

### ISSUE THREAD

**Issue by cdransf** [805developershub/805-Developers-Hub-Website#2]
We need to decide on the best way to host and deploy the Jekyll 805 Developers Site. I have a VPS we can host it on or we can look at static hosting like that provided by Github Pages. Open to other options as well.

**Comment by clemtibs** [comment]
My vote is for Github pages for following reasons:

- free
- good to learn in general/skills widely applicable for individuals to use on their own sites
- push access alone is enough for someone to contribute to the site without needing to involve private servers etc.

I've used github pages and can help with adding build script and some instructions etc.

**Comment by smeads** [comment]
My vote would be for GitHub pages as well. I think if we can have the site mostly ready to push to production for next week meetup, then we could provide a great learning opportunity by showing those who have never hosted or deployed an application before to see how it's done.

**Comment by cdransf** [comment]
That sounds great to me. I may have a few images we can use to replace the stock theme images as well.
